
import '@/styles/globals.scss'
import { Inter } from 'next/font/google'

import SideNav from "@/components/SideNav"
import Header from '@/components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className + " "}>
        <Header />
        <main>
          <SideNav />
          <div className='lg:pl-72 pt-16'>
            <div className='mx-auto'>
              {children}
            </div>
          </div>

        </main>
      </body>
    </html>
  )
}
