// 'use client'
// import '@/styles/globals.scss'
import { Inter } from "next/font/google";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params
}: {
  children: React.ReactNode;
}) {
  // const pathname = usePathname()
  // console.log(params)
  return (
    <div className={"flex flex-col pt-4 px-6 space-y-3"}>
      
      {/* <h1 className="lg:text-2xl font-bold">Dashboard</h1> */}
      {children}
    </div>
  );
}
